### ISSUE TITLE
this line 47 seems corrupted - preprocess_yafc.py

### ISSUE THREAD

**Issue by johndpope** [p-kar/text-style-transfer-gan#1]
transtab = str.maketrans('éè—üəāöóŕ–ƒùšïĕ§†ûàäñıáí', 'ee ueaoor fusiestuaaniai', string.punctuation + '¢®£©´™“’”¿¨…\u200b綠嘉豆加因人為義薏仁»œ►•·ºس恭¹♡¡λ發‘˝◄½م喜♥☺æها財')

**Comment by p-kar** [comment]
The YAFC dataset contains a lot of junk characters (because it is generated from the Yahoo answers web crawl), some places they can be replaced with english characters other places they have to be deleted altogether. This line helps us do that, it basically creates a translation table. I know there are better ways of doing this, I will clean this up in the future.

**Comment by johndpope** [comment]
thanks for reply.
